/* NSC -- new Scala compiler
 * Copyright 2005-2011 LAMP/EPFL
 * @author  Martin Odersky
 */

package scala.tools.nsc

<<<<<<< HEAD
import util.{ FreshNameCreator,Position,NoPosition,SourceFile }
=======
import util.{ FreshNameCreator, Position, NoPosition, SourceFile, NoSourceFile }
>>>>>>> 426c65030df3df0c3e038931b64199fc4e83c1a0
import scala.collection.mutable
import scala.collection.mutable.{ LinkedHashSet, ListBuffer }

trait CompilationUnits { self: Global =>

<<<<<<< HEAD
=======
  /** An object representing a missing compilation unit.
   */
  object NoCompilationUnit extends CompilationUnit(NoSourceFile) {
    override lazy val isJava = false
    override def exists = false
    override def toString() = "NoCompilationUnit"
  }

>>>>>>> 426c65030df3df0c3e038931b64199fc4e83c1a0
  /** One unit of compilation that has been submitted to the compiler.
    * It typically corresponds to a single file of source code.  It includes
    * error-reporting hooks.  */
  class CompilationUnit(val source: SourceFile) {

    /** the fresh name creator */
    var fresh: FreshNameCreator = new FreshNameCreator.Default
<<<<<<< HEAD
    
=======

>>>>>>> 426c65030df3df0c3e038931b64199fc4e83c1a0
    def freshTermName(prefix: String): TermName = newTermName(fresh.newName(prefix))
    def freshTypeName(prefix: String): TypeName = newTypeName(fresh.newName(prefix))

    /** the content of the compilation unit in tree form */
    var body: Tree = EmptyTree

<<<<<<< HEAD
=======
    def exists = source != NoSourceFile && source != null

>>>>>>> 426c65030df3df0c3e038931b64199fc4e83c1a0
//    def parseSettings() = {
//      val argsmarker = "SCALAC_ARGS"
//      if(comments nonEmpty) {
//        val pragmas = comments find (_.text.startsWith("//#")) // only parse first one
//        pragmas foreach { p =>
//          val i = p.text.indexOf(argsmarker)
//          if(i > 0)
//        }
//      }
//    }
    /** Note: depends now contains toplevel classes.
     *  To get their sourcefiles, you need to dereference with .sourcefile
     */
    val depends = mutable.HashSet[Symbol]()

<<<<<<< HEAD
    /** so we can relink 
=======
    /** so we can relink
>>>>>>> 426c65030df3df0c3e038931b64199fc4e83c1a0
     */
    val defined = mutable.HashSet[Symbol]()

    /** Synthetic definitions generated by namer, eliminated by typer.
     */
    val synthetics = mutable.HashMap[Symbol, Tree]()

    /** things to check at end of compilation unit */
    val toCheck = new ListBuffer[() => Unit]

    def position(pos: Int) = source.position(pos)

    /** The position of a targeted type check
     *  If this is different from NoPosition, the type checking
     *  will stop once a tree that contains this position range
     *  is fully attributed.
     */
    def targetPos: Position = NoPosition

    /** The icode representation of classes in this compilation unit.
     *  It is empty up to phase 'icode'.
     */
    val icode: LinkedHashSet[icodes.IClass] = new LinkedHashSet

    def error(pos: Position, msg: String) =
      reporter.error(pos, msg)

<<<<<<< HEAD
    def warning(pos: Position, msg: String) = 
      reporter.warning(pos, msg)

    def deprecationWarning(pos: Position, msg: String) = 
      if (opt.deprecation) warning(pos, msg)
      else currentRun.deprecationWarnings += 1

    def uncheckedWarning(pos: Position, msg: String) = 
      if (opt.unchecked) warning(pos, msg)
      else currentRun.uncheckedWarnings += 1

    def incompleteInputError(pos: Position, msg:String) =
      reporter.incompleteInputError(pos, msg) 

    def comment(pos: Position, msg: String) =
      reporter.comment(pos, msg)
      
    /** Is this about a .java source file? */
    lazy val isJava = source.file.name.endsWith(".java")
    
=======
    def warning(pos: Position, msg: String) =
      reporter.warning(pos, msg)

    def deprecationWarning(pos: Position, msg: String) =
      if (opt.deprecation) warning(pos, msg)
      else currentRun.deprecationWarnings ::= ((pos, msg))

    def uncheckedWarning(pos: Position, msg: String) =
      if (opt.unchecked) warning(pos, msg)
      else currentRun.uncheckedWarnings ::= ((pos, msg))

    def incompleteInputError(pos: Position, msg:String) =
      reporter.incompleteInputError(pos, msg)

    def comment(pos: Position, msg: String) =
      reporter.comment(pos, msg)

    /** Is this about a .java source file? */
    lazy val isJava = source.file.name.endsWith(".java")

>>>>>>> 426c65030df3df0c3e038931b64199fc4e83c1a0
    override def toString() = source.toString()

    def clear() {
      fresh = null
      body = null
      depends.clear()
      defined.clear()
    }
  }
}


